routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['register' => false, 'reset' => false]);

Route::middleware('auth')->group(function () {
    Route::get('/change-password', 'AuthController@changePassword')->name('change_password');
    Route::post('/change-password', 'AuthController@postChangePassword');

    Route::get('/', 'HomeController@index')->name('index');

    Route::prefix('users')->name('user.')->group(function () {
        Route::middleware('can:users_list')->group(function () {
            Route::get('/', 'UserController@index')->name('index');
            Route::post('/data-table', 'UserController@getDataTable');
        });

        Route::middleware('can:users_create')->group(function () {
            Route::get('/create', 'UserController@create')->name('create');
            Route::post('/store', 'UserController@store')->name('store');
        });

        Route::middleware('can:users_update')->group(function () {
            Route::get('/edit/{id}', 'UserController@edit')->name('edit');
            Route::post('/edit/{id}', 'UserController@update')->name('update');
        });

        Route::post('change-status', 'UserController@changeStatus')->middleware('can:users_change_status');
        Route::post('/reset-password', 'UserController@resetPassword')->middleware('can:users_reset_password');
    });

    Route::prefix('profiles')->name('profile.')->group(function () {
        Route::post('/data-table', 'ProfileController@getDataTable');
        Route::get('/', 'ProfileController@index')->name('index');

        Route::middleware('can:profiles_import')->group(function () {
            Route::get('/create', 'ProfileController@create')->name('create');
            Route::post('/create', 'ProfileController@store')->name('store');
        });

        Route::middleware('can:profiles_import')->group(function () {
            Route::get('/import', 'ProfileController@getImportFile')->name('import');
            Route::post('/import', 'ProfileController@postImportFile');
            Route::post('/import-save', 'ProfileController@saveImport');
        });

        Route::middleware('can:profiles_update')->group(function () {
            Route::get('edit/{id}', 'ProfileController@edit')->name('edit');
            Route::post('edit/{id}', 'ProfileController@update')->name('update');
        });

        Route::post('/delete', 'ProfileController@delete')->middleware('role:admin');

        Route::middleware('can:accountants_create')->name('fee.')->group(function () {
            Route::post('fee', 'ProfileController@storeFee')->name('store');
        });

        Route::get('/{id}', 'ProfileController@show')->name('show');
    });

    Route::prefix('accountants')->name('accountant.')->group(function () {
        Route::middleware('can:accountants_list')->group(function () {
            Route::get('/', 'AccountantController@index')->name('index');
            Route::post('income/data-table', 'AccountantController@getIncomeDataTable');
            Route::post('outcome/data-table', 'AccountantController@getOutcomeDataTable');

            Route::post('get-sum', 'AccountantController@getSum');
            Route::post('profiles/{id}', 'AccountantController@profile');
        });

        Route::middleware('can:accountants_create')->group(function () {
            Route::get('/create', 'AccountantController@create')->name('create');
            Route::post('/store', 'AccountantController@store')->name('store');
        });

        Route::middleware('can:accountants_update')->group(function () {
            Route::get('/edit/{id}', 'AccountantController@edit')->name('edit');
            Route::post('/edit/{id}', 'AccountantController@update')->name('update');
        });

        Route::post('/delete', 'AccountantController@delete')->middleware('role:admin');

        Route::prefix('ajax')->group(function () {
            Route::get('deposit', 'AccountantController@ajaxShowDeposit');
            Route::post('deposit', 'AccountantController@ajaxUpdateDeposit');
        });
    });

    Route::prefix('district')->name('district.')->group(function () {
        Route::get('/get-from-city/{city_id}', 'DistrictController@getFromCity');
    });
});

app/Models/User.php
<?php

namespace App\Models;

use App\Models\Traits\HasRoles;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable, SoftDeletes, HasRoles;

    // const ROLE_ADMIN = 0;
    // const ROLE_MARKETING = 1;
    // const ROLE_TELE_SALE = 2;
    // const ROLE_ACCOUNTANT = 3;

    // const ROLE_LIST = [
    //     self::ROLE_ADMIN => 'Admin',
    //     self::ROLE_MARKETING => 'Marketer',
    //     self::ROLE_TELE_SALE => 'TeleSale',
    //     self::ROLE_ACCOUNTANT => 'Accountant',
    // ];

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token'
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    protected $with = ['roles.permissions', 'permissions'];

    public function setPasswordAttribute($value)
    {
        $this->attributes['password'] = bcrypt($value);
    }

    /** Relationship 1 - n */
    public function accountants()
    {
        return $this->hasMany('App\Models\Accountant');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Core\Business\Contracts\UserInterface;
use Illuminate\Http\Request;

class UserController extends Controller
{
    protected $userBusiness;

    public function __construct(UserInterface $userBusiness)
    {
        $this->userBusiness = $userBusiness;
    }

    public function index()
    {
        $data = $this->userBusiness->index();

        return view('user.index')->with($data);
    }

    public function create()
    {
        $data = $this->userBusiness->create();

        return view('user.create')->with($data);
    }

    public function store(Request $request)
    {
        $request->validate([
            'email' => 'unique:users'
        ]);

        $data = $request->only(['name', 'email', 'password', 'permission_ids']);

        $result = $this->userBusiness->store($data);

        if ($result) {
            return redirect()->route('user.index')->with(['create_user' => true]);
        }

        return back()->withInput()->withErrors(['message' => 'Have error while creating User']);
    }

    public function edit($id)
    {
        $data = $this->userBusiness->edit($id);

        return view('user.edit')->with($data);
    }

    public function update(Request $request, $id)
    {
        $data = $request->only(['name', 'permission_ids']);

        $result = $this->userBusiness->update($id, $data);

        if ($result) {
            return redirect()->route('user.index')->with(['update_user' => true]);
        }

        return back()->withInput()->withErrors(['message' => 'Have error while updating User']);
    }

    public function resetPassword(Request $request)
    {
        $id = $request->id;

        $result = $this->userBusiness->resetPassword($id);

        return response()->json($result);
    }

    public function getDataTable(Request $request)
    {
        return $this->userBusiness->getTableData($request);
    }

    public function changeStatus(Request $request)
    {
        $status = $this->userBusiness->changeStatus($request->id);

        return response()->json(['status' => $status], 200);
    }
}

resources/views/user/create.blade.php
@extends('layouts.master')

@section('title', 'User Create | English Homestay')

@section('plugin_stylesheets')
<link rel="stylesheet" href="{{ asset('vendors/admin-lte-3.0.5/plugins/select2/css/select2.min.css') }}">
<link rel="stylesheet"
    href="{{ asset('vendors/admin-lte-3.0.5/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css') }}">
<!-- summernote -->
<link rel="stylesheet" href="{{ asset('vendors/admin-lte-3.0.5/plugins/summernote/summernote-bs4.css') }}">
@endsection


@section('content')
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>
                    User
                </h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="{{ route('index') }}">Home</a></li>
                    <li class="breadcrumb-item"><a href="{{ route('user.index') }}">User</a></li>
                    <li class="breadcrumb-item active">Create</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <!-- Filter -->
                <div class="card card-primary card-outline">
                    <div class="card-header">
                        <h3 class="card-title">
                            Add New User
                        </h3>
                    </div>
                    <div class="card-body">
                        <form role="form" method="POST" action="{{ route('user.store') }}" id="user-create-form">
                            @csrf
                            <div class="row">
                                <div class="col-12 col-md-4">
                                    <div class="form-group">
                                        <label for="name">Họ tên</label>
                                        <input id="name" type="text"
                                            class="form-control @error('name') is-invalid @enderror" name="name"
                                            value="{{ old('name') }}" required>
                                        @error('name')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                        @enderror
                                    </div>
                                </div>
                                <div class="col-12 col-md-4">
                                    <div class="form-group">
                                        <label for="email">Email</label>
                                        <input type="email" name="email" id="email"
                                            class="form-control @error('email') is-invalid @enderror"
                                            value="{{ old('email') }}" required>
                                        @error('email')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                        @enderror
                                    </div>
                                </div>
                                <div class="col-12 col-md-4">
                                    <div class="form-group">
                                        <label for="password">Password</label>
                                        <input type="text" name="password" id="password" class="form-control"
                                            value="{{ old('passowrd') ?? Str::random(10) }}" required>
                                    </div>
                                </div>
                                <div class="col-12 col-md-12">
                                    <div class="form-group">
                                        <label for="role">Quyền hạn</label>
                                        <div class="w-100">
                                            @foreach($roleList as $role)
                                            <p class="d-block bg-light py-2 px-3 rounded">
                                                {{ ucwords(__('roles.display_name.'.$role->name)) }}</p>

                                            <div class="py-2 px-3 d-flex mb-3">
                                                @foreach($role->permissions as $permission)
                                                <div class="form-check form-check-inline mr-3">
                                                    <input class="form-check-input" type="checkbox"
                                                        name="permission_ids[]" id="{{ $permission->name }}"
                                                        value="{{ $permission->id }}">
                                                    <label class="form-check-label"
                                                        for="{{ $permission->name }}">{{ ucwords(__('permissions.display_name.'.$permission->name)) }}</label>
                                                </div>
                                                @endforeach
                                            </div>
                                            @endforeach
                                        </div>
                                    </div>
                                </div>
                                <div class="col-12 text-center">
                                    <button type="submit" class="btn btn-primary">Submit</button>
                                    <a href="{{ route('profile.index') }}" type="button"
                                        class="btn btn-warning">Cancel</a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
                <!-- End Filter -->
            </div>
        </div>
    </div>
</section>
@endsection

@section('plugin_scripts')
<!-- Select2 -->
<script src="{{ asset('vendors/admin-lte-3.0.5/plugins/select2/js/select2.full.min.js') }}"></script>

<!-- Summernote -->
<script src="{{ asset('vendors/admin-lte-3.0.5/plugins/summernote/summernote-bs4.min.js') }}"></script>
@endsection

@section('scripts')
<script src="{{ mix('js/user.js') }}"></script>
@endsection

resources/views/user/edit.blade.php
@extends('layouts.master')

@section('title', 'User Create | English Homestay')

@section('plugin_stylesheets')
<link rel="stylesheet" href="{{ asset('vendors/admin-lte-3.0.5/plugins/select2/css/select2.min.css') }}">
<link rel="stylesheet"
    href="{{ asset('vendors/admin-lte-3.0.5/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css') }}">
<!-- summernote -->
<link rel="stylesheet" href="{{ asset('vendors/admin-lte-3.0.5/plugins/summernote/summernote-bs4.css') }}">
@endsection


@section('content')
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>
                    User
                </h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="{{ route('index') }}">Home</a></li>
                    <li class="breadcrumb-item"><a href="{{ route('user.index') }}">User</a></li>
                    <li class="breadcrumb-item active">Update</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <!-- Filter -->
                <div class="card card-primary card-outline">
                    <div class="card-header">
                        <h3 class="card-title">
                            Update User Info
                        </h3>
                    </div>
                    <div class="card-body">
                        <form role="form" method="POST" action="{{ route('user.update', ['id' => $userItem->id]) }}"
                            id="user-create-form">
                            @csrf
                            <div class="row">
                                <div class="col-12 col-md-4">
                                    <div class="form-group">
                                        <label for="name">Họ tên</label>
                                        <input id="name" type="text"
                                            class="form-control @error('name') is-invalid @enderror" name="name"
                                            value="{{ old('name') ?? $userItem->name }}" required>
                                        @error('name')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                        @enderror
                                    </div>
                                </div>
                                <div class="col-12 col-md-4">
                                    <div class="form-group">
                                        <label for="email">Email</label>
                                        <input type="email" name="email" id="email" class="form-control"
                                            value="{{ $userItem->email }}" disabled>
                                        @error('email')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                        @enderror
                                    </div>
                                </div>
                                <div class="col-12 col-md-4">
                                    <div class="form-group">
                                        <label for="password">Password</label>
                                        <input type="password" name="password" id="password" class="form-control"
                                            value="{{ Str::random(10) }}" disabled>
                                    </div>
                                </div>
                                <div class="col-12 col-md-12">
                                    <div class="form-group">
                                        <label for="role">Quyền hạn</label>
                                        <div class="w-100">
                                            @foreach($roleList as $role)
                                            <p class="d-block bg-light py-2 px-3 rounded">
                                                {{ ucwords(__('roles.display_name.'.$role->name)) }}</p>

                                            <div class="py-2 px-3 d-flex mb-3">
                                                @foreach($role->permissions as $permission)
                                                <div class="form-check form-check-inline mr-3">
                                                    <input class="form-check-input" type="checkbox"
                                                        name="permission_ids[]" id="{{ $permission->name }}"
                                                        value="{{ $permission->id }}"
                                                        {{ $userItem->hasPermissionTo($permission) ? 'checked' : ''}}>
                                                    <label class="form-check-label"
                                                        for="{{ $permission->name }}">{{ ucwords(__('permissions.display_name.'.$permission->name)) }}</label>
                                                </div>
                                                @endforeach
                                            </div>
                                            @endforeach
                                        </div>
                                    </div>
                                </div>
                                <div class="col-12 text-center">
                                    <button type="submit" class="btn btn-primary">Submit</button>
                                    <a href="{{ route('profile.index') }}" type="button"
                                        class="btn btn-warning">Cancel</a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
                <!-- End Filter -->
            </div>
        </div>
    </div>
</section>
@endsection

@section('plugin_scripts')
<!-- Select2 -->
<script src="{{ asset('vendors/admin-lte-3.0.5/plugins/select2/js/select2.full.min.js') }}"></script>

<!-- Summernote -->
<script src="{{ asset('vendors/admin-lte-3.0.5/plugins/summernote/summernote-bs4.min.js') }}"></script>
@endsection

@section('scripts')
<script src="{{ mix('js/user.js') }}"></script>
@endsection

resources/views/user/index.blade.php
@extends('layouts.master')

@section('title', 'Users | English Homestay')

@section('plugin_stylesheets')
<!-- DataTables -->
<link rel="stylesheet"
    href="{{ asset('vendors/admin-lte-3.0.5/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css') }}">
<link rel="stylesheet"
    href="{{ asset('vendors/admin-lte-3.0.5/plugins/datatables-responsive/css/responsive.bootstrap4.min.css') }}">
<!-- SweetAlert2 -->
<link rel="stylesheet"
    href="{{ asset('vendors/admin-lte-3.0.5/plugins/sweetalert2-theme-bootstrap-4/bootstrap-4.min.css') }}">
<link rel="stylesheet" href="{{ asset('vendors/admin-lte-3.0.5/plugins/select2/css/select2.min.css') }}">
<link rel="stylesheet"
    href="{{ asset('vendors/admin-lte-3.0.5/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css') }}">
@endsection

@section('stylesheets')
<style>
    .badge-1 {
        color: #fff;
        background-color: #17a2b8;
    }

    .badge-2 {
        color: #fff;
        background-color: #007bff;
    }

    #submit-btn-search {
        margin-bottom: 1rem;
    }

    @media (min-width: 768px) {

        #submit-btn-search,
        #reset-btn-search {
            margin-top: 2rem;
        }

        #submit-btn-search {
            margin-bottom: 0;
        }
    }
</style>
@endsection

@section('content')
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>
                    Users <a href="{{ route('user.create') }}" class="btn btn-success btn-xs">Add New</a>
                </h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="{{ route('index') }}">Home</a></li>
                    <li class="breadcrumb-item active">Users</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <!-- Filter -->
                <div class="card card-primary card-outline">
                    <div class="card-header">
                        <h3 class="card-title">
                            <i class="fas fa-edit"></i>
                            Filter
                        </h3>
                    </div>
                    <div class="card-body">
                        <form role="form" id="user-filter">
                            <div class="row">
                                <div class="col-12 col-md-6">
                                    <div class="form-group">
                                        <label for="search-keyword">Search Keyword</label>
                                        <input type="text" name="search_keyword" id="search-keyword"
                                            class="form-control">
                                    </div>
                                </div>
                                <div class="col-12 col-md-3">
                                    <div class="form-group">
                                        <label for="permission-ids">Role</label>
                                        <select class="form-control select2bs4" multiple id="permission-ids"
                                            name="permission_ids[]" style="width: 100%;">
                                            @foreach($roleList as $role)
                                            @foreach($role->permissions as $permission)
                                            <option value="{{ $permission->id }}">
                                                {{ ucwords(__('permissions.display_name.'.$permission->name)) }}
                                            </option>
                                            @endforeach
                                            @endforeach
                                        </select>
                                    </div>
                                </div>
                                <div class="col-12 col-md-3">
                                    <div class="row">
                                        <div class="col-12 col-md-6">
                                            <button id="submit-btn-search" type="submit"
                                                class="btn btn-primary btn-block">Submit</button>
                                        </div>
                                        <div class="col-12 col-md-6">
                                            <button id="reset-btn-search" type="button"
                                                class="btn btn-warning btn-block">Reset</button>
                                        </div>
                                    </div>

                                </div>
                            </div>
                        </form>
                    </div>
                </div>
                <!-- End Filter -->

                <!-- DataTable -->
                <div class="card">
                    <div class="card-body">
                        <table id="user-datatable" class="table table-bordered table-striped table-hover">
                            <thead>
                                <tr class="text-center">
                                    <th>ID</th>
                                    <th>Name</th>
                                    <th>Email</th>
                                    <th>Roles - Permissions</th>
                                    <th>Status</th>
                                    <th>Timestamps</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                            </tbody>
                            <tfoot>
                                <tr class="text-center">
                                    <th>ID</th>
                                    <th>Name</th>
                                    <th>Email</th>
                                    <th>Roles - Permissions</th>
                                    <th>Status</th>
                                    <th>Timestamps</th>
                                    <th>Action</th>
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>
                <!-- End DataTable -->
            </div>
        </div>
    </div>
</section>
@endsection


@section('plugin_scripts')
<script src="{{ asset('vendors/admin-lte-3.0.5/plugins/moment/moment.min.js') }}"></script>

<!-- DataTables -->
<script src="{{ asset('vendors/admin-lte-3.0.5/plugins/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('vendors/admin-lte-3.0.5/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js') }}"></script>
<script src="{{ asset('vendors/admin-lte-3.0.5/plugins/datatables-responsive/js/dataTables.responsive.min.js') }}">
</script>
<script src="{{ asset('vendors/admin-lte-3.0.5/plugins/datatables-responsive/js/responsive.bootstrap4.min.js') }}">
</script>
<!-- SweetAlert2 -->
<script src="{{ asset('vendors/admin-lte-3.0.5/plugins/sweetalert2/sweetalert2.min.js') }}"></script>
<!-- Select2 -->
<script src="{{ asset('vendors/admin-lte-3.0.5/plugins/select2/js/select2.full.min.js') }}"></script>
@endsection

@section('scripts')
@if(session('create_user'))
<script>
    window.createUser = true;
</script>
@endif
@if(session('update_user'))
<script>
    window.updateUser = true;
</script>
@endif
<script src="{{ mix('js/user.js') }}"></script>
@endsection