routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['register' => false, 'reset' => false]);

Route::middleware('auth')->group(function () {
    Route::get('/change-password', 'AuthController@changePassword')->name('change_password');
    Route::post('/change-password', 'AuthController@postChangePassword');

    Route::get('/', 'HomeController@index')->name('index');

    Route::prefix('users')->name('user.')->group(function () {
        Route::middleware('can:users_list')->group(function () {
            Route::get('/', 'UserController@index')->name('index');
            Route::post('/data-table', 'UserController@getDataTable');
        });

        Route::middleware('can:users_create')->group(function () {
            Route::get('/create', 'UserController@create')->name('create');
            Route::post('/store', 'UserController@store')->name('store');
        });

        Route::middleware('can:users_update')->group(function () {
            Route::get('/edit/{id}', 'UserController@edit')->name('edit');
            Route::post('/edit/{id}', 'UserController@update')->name('update');
        });

        Route::post('change-status', 'UserController@changeStatus')->middleware('can:users_change_status');
        Route::post('/reset-password', 'UserController@resetPassword')->middleware('can:users_reset_password');
    });

    Route::prefix('profiles')->name('profile.')->group(function () {
        Route::post('/data-table', 'ProfileController@getDataTable');
        Route::get('/', 'ProfileController@index')->name('index');

        Route::middleware('can:profiles_import')->group(function () {
            Route::get('/create', 'ProfileController@create')->name('create');
            Route::post('/create', 'ProfileController@store')->name('store');
        });

        Route::middleware('can:profiles_import')->group(function () {
            Route::get('/import', 'ProfileController@getImportFile')->name('import');
            Route::post('/import', 'ProfileController@postImportFile');
            Route::post('/import-save', 'ProfileController@saveImport');
        });

        Route::middleware('can:profiles_update')->group(function () {
            Route::get('edit/{id}', 'ProfileController@edit')->name('edit');
            Route::post('edit/{id}', 'ProfileController@update')->name('update');
        });

        Route::post('/delete', 'ProfileController@delete')->middleware('role:admin');

        Route::middleware('can:accountants_create')->name('fee.')->group(function () {
            Route::post('fee', 'ProfileController@storeFee')->name('store');
        });

        Route::get('/{id}', 'ProfileController@show')->name('show');
    });

    Route::prefix('accountants')->name('accountant.')->group(function () {
        Route::middleware('can:accountants_list')->group(function () {
            Route::get('/', 'AccountantController@index')->name('index');
            Route::post('income/data-table', 'AccountantController@getIncomeDataTable');
            Route::post('outcome/data-table', 'AccountantController@getOutcomeDataTable');

            Route::post('get-sum', 'AccountantController@getSum');
            Route::post('profiles/{id}', 'AccountantController@profile');
        });

        Route::middleware('can:accountants_create')->group(function () {
            Route::get('/create', 'AccountantController@create')->name('create');
            Route::post('/store', 'AccountantController@store')->name('store');
        });

        Route::middleware('can:accountants_update')->group(function () {
            Route::get('/edit/{id}', 'AccountantController@edit')->name('edit');
            Route::post('/edit/{id}', 'AccountantController@update')->name('update');
        });

        Route::post('/delete', 'AccountantController@delete')->middleware('role:admin');

        Route::prefix('ajax')->group(function () {
            Route::get('deposit', 'AccountantController@ajaxShowDeposit');
            Route::post('deposit', 'AccountantController@ajaxUpdateDeposit');
        });
    });

    Route::prefix('district')->name('district.')->group(function () {
        Route::get('/get-from-city/{city_id}', 'DistrictController@getFromCity');
    });
});

app/Models/Accountant.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Auth;

class Accountant extends Model
{
    use SoftDeletes;

    const INCOME_ID = 1;
    const OUTCOME_ID = 2;
    const DEPOSIT_ID = 3;

    const ACCOUNTANT_CREATE = 'accountants_create';

    protected static function booted()
    {
        static::creating(function ($profile) {
            $profile->fill([
                'user_id' => Auth::id()
            ]);
        });

        static::updating(function ($profile) {
            $profile->fill([
                'user_id' => Auth::id()
            ]);
        });
    }

    protected $table = 'accountants';

    protected $fillable = [
        'profile_id', 'type_id', 'user_id', 'money', 'explain'
    ];

    protected $casts = [
        'created_at' => 'datetime:d/m/Y H:i:s',
        'updated_at' => 'datetime:d/m/Y H:i:s',
    ];

    /** Relationship  n - 1 */
    public function profile()
    {
        return $this->belongsTo('App\Models\Profile');
    }

    public function user()
    {
        return $this->belongsTo('App\Models\User');
    }

    /** Scopes */
    public function scopeOnlyIncome(Builder $builder)
    {
        return $builder->whereIn('type_id', [self::INCOME_ID, self::DEPOSIT_ID]);
    }

    public function scopeOnlyOutcome(Builder $builder)
    {
        return $builder->where('type_id', self::OUTCOME_ID);
    }
}

app/Http/Controllers/AccountantController.php
<?php

namespace App\Http\Controllers;

use App\Core\Business\Contracts\AccountantInterface as AccountantBusiness;
use App\Models\Accountant;
use Carbon\Carbon;
use Illuminate\Http\Request;

class AccountantController extends Controller
{
    protected $accountantBusiness;

    public function __construct(AccountantBusiness $accountantBusiness)
    {
        $this->accountantBusiness = $accountantBusiness;
    }

    public function index(Request $request)
    {
        $data = $this->accountantBusiness->index($request);

        return view('accountant.index')->with($data);
    }

    public function create()
    {
        return view('accountant.create');
    }

    public function store(Request $request)
    {
        $request->validate([
            'money' => 'required|numeric',
            'type_id' => 'required|in:' . implode(',', [Accountant::INCOME_ID, Accountant::OUTCOME_ID]),
            'explain' => 'required',
        ], [
            'money.required' => 'Vui lòng nhập số tiền.',
            'money.numeric' => 'Số tiền phải là số.',
            'type_id.required' => 'Vui lòng chọn loại',
            'type_id.in' => 'Giá trị loại không đúng!',
            'explain.required' => 'Vui lòng ghi chú nội dung.',
        ]);

        $result = $this->accountantBusiness->store($request->except(['_token']));

        if ($result['success']) {
            return redirect()->route('accountant.index')->with('create_accountant', true);
        }

        return back()->withInput()->withErrors(['message' => $result['message']]);
    }

    public function edit($id)
    {
        $data = $this->accountantBusiness->edit($id);

        return view('accountant.edit')->with($data);
    }

    public function update(Request $request, $id)
    {
        $request->validate([
            'money' => 'required|numeric',
            'type_id' => 'required|in:' . implode(',', [Accountant::INCOME_ID, Accountant::OUTCOME_ID]),
            'explain' => 'required',
        ], [
            'money.required' => 'Vui lòng nhập số tiền.',
            'money.numeric' => 'Số tiền phải là số.',
            'type_id.required' => 'Vui lòng chọn loại',
            'type_id.in' => 'Giá trị loại không đúng!',
            'explain.required' => 'Vui lòng ghi chú nội dung.',
        ]);

        $result = $this->accountantBusiness->update($id, $request->except(['_token']));

        if ($result['success']) {
            return redirect()->route('accountant.index')->with('update_accountant', true);
        }

        return back()->withInput()->withErrors(['message' => $result['message']]);
    }

    public function delete(Request $request)
    {
        return $this->accountantBusiness->destroy($request->id);
    }

    public function getIncomeDataTable()
    {
        return $this->accountantBusiness->getTableData(Accountant::INCOME_ID);
    }

    public function getOutcomeDataTable()
    {
        return $this->accountantBusiness->getTableData(Accountant::OUTCOME_ID);
    }

    public function profile($id)
    {
        return response()->json(
            $this->accountantBusiness->getProfileFeeDetail($id)
        );
    }

    public function getSum(Request $request)
    {
        $request->validate([
            'from_date' => 'required',
            'to_date' => 'required',
        ]);

        $fromDate = Carbon::createFromFormat('d/m/Y', Request()->from_date)->startOfDay()->format('Y-m-d H:i:s');
        $toDate = Carbon::createFromFormat('d/m/Y', Request()->to_date)->endOfDay()->format('Y-m-d H:i:s');

        return response()->json(
            $this->accountantBusiness->getSum($fromDate, $toDate)
        );
    }

    public function ajaxShowDeposit(Request $request)
    {
        return response()->json(
            $this->accountantBusiness->getProfileDepositDetail($request->accountant_id, $request->profile_id)
        );
    }

    public function ajaxUpdateDeposit(Request $request)
    {
        $request->validate([
            'profile_id' => 'required|numeric',
            'money' => 'required|numeric',
            'explain' => 'required'
        ]);

        return response()->json([
            $this->accountantBusiness->updateProfileDepositDetail($request->accountant_id ?? 0, $request->except(['_token', 'accountant_id']))
        ]);
    }
}

resources/views/accountant/create.blade.php
@extends('layouts.master')

@section('title', 'Accountants Create | English Homestay')

@section('plugin_stylesheets')
<link rel="stylesheet" href="{{ asset('vendors/admin-lte-3.0.5/plugins/select2/css/select2.min.css') }}">
<link rel="stylesheet"
    href="{{ asset('vendors/admin-lte-3.0.5/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css') }}">
<!-- summernote -->
<link rel="stylesheet" href="{{ asset('vendors/admin-lte-3.0.5/plugins/summernote/summernote-bs4.css') }}">
@endsection


@section('content')
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>
                    Accountant
                </h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="{{ route('index') }}">Home</a></li>
                    <li class="breadcrumb-item"><a href="{{ route('accountant.index') }}">Accountant</a></li>
                    <li class="breadcrumb-item active">Create</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <!-- Filter -->
                <div class="card card-primary card-outline">
                    <div class="card-header">
                        <h3 class="card-title">
                            Tạo mới thu chi
                        </h3>
                    </div>
                    <div class="card-body">
                        <form role="form" method="POST" action="{{ route('accountant.store') }}"
                            id="accountant-create-form">
                            @csrf
                            <div class="row">
                                <div class="col-12 col-md-6">
                                    <div class="form-group">
                                        <label for="money">Số tiền</label>
                                        <input id="money" type="text"
                                            class="form-control @error('money') is-invalid @enderror" name="money"
                                            value="{{ old('money') }}" required>
                                        @error('money')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                        @enderror
                                    </div>
                                </div>
                                <div class="col-12 col-md-6">
                                    <div class="form-group">
                                        <label for="type-id">Type</label>
                                        <select class="select2bs4 form-control" name="type_id" id="type-id">
                                            <option value="{{ \App\Models\Accountant::INCOME_ID }}">Thu</option>
                                            <option value="{{ \App\Models\Accountant::OUTCOME_ID }}">Chi</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-12">
                                    <div class="form-group">
                                        <label for="explain">Note</label>
                                        <textarea class="form-control" id="explain" name="explain"
                                            required>{{ old('explain') }}</textarea>
                                    </div>
                                </div>
                                <div class="col-12 text-center">
                                    <button type="submit" class="btn btn-primary">Submit</button>
                                    <a href="{{ route('accountant.index') }}" type="button"
                                        class="btn btn-warning">Cancel</a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
                <!-- End Filter -->
            </div>
        </div>
    </div>
</section>
@endsection

@section('plugin_scripts')
<!-- Select2 -->
<script src="{{ asset('vendors/admin-lte-3.0.5/plugins/select2/js/select2.full.min.js') }}"></script>

<!-- Summernote -->
<script src="{{ asset('vendors/admin-lte-3.0.5/plugins/summernote/summernote-bs4.min.js') }}"></script>
@endsection

@section('scripts')
<script src="{{ mix('js/accountant.js') }}"></script>
@endsection

resources/views/accountant/edit.blade.php
@extends('layouts.master')

@section('title', 'Accountants Create | English Homestay')

@section('plugin_stylesheets')
<link rel="stylesheet" href="{{ asset('vendors/admin-lte-3.0.5/plugins/select2/css/select2.min.css') }}">
<link rel="stylesheet"
    href="{{ asset('vendors/admin-lte-3.0.5/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css') }}">
<!-- summernote -->
<link rel="stylesheet" href="{{ asset('vendors/admin-lte-3.0.5/plugins/summernote/summernote-bs4.css') }}">
@endsection


@section('content')
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>
                    Accountant
                </h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="{{ route('index') }}">Home</a></li>
                    <li class="breadcrumb-item"><a href="{{ route('accountant.index') }}">Accountant</a></li>
                    <li class="breadcrumb-item active">Update</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <!-- Filter -->
                <div class="card card-primary card-outline">
                    <div class="card-header">
                        <h3 class="card-title">
                            Chỉnh sửa thu chi
                        </h3>
                    </div>
                    <div class="card-body">
                        <form role="form" method="POST" action="{{ route('accountant.update', $accountantItem->id) }}"
                            id="accountant-create-form">
                            @csrf
                            <div class="row">
                                <div class="col-12 col-md-6">
                                    <div class="form-group">
                                        <label for="money">Số tiền</label>
                                        <input id="money" type="text"
                                            class="form-control @error('money') is-invalid @enderror" name="money"
                                            value="{{ old('money') ?? $accountantItem->money }}" required>
                                        @error('money')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                        @enderror
                                    </div>
                                </div>
                                <div class="col-12 col-md-6">
                                    <div class="form-group">
                                        <label for="type-id">Type</label>
                                        <select class="select2bs4 form-control" name="type_id" id="type-id">
                                            <option value="{{ \App\Models\Accountant::INCOME_ID }}"
                                                {{ (old('type_id') ?? $accountantItem->type_id) == \App\Models\Accountant::INCOME_ID ? 'selected' : '' }}>
                                                Thu</option>
                                            <option value="{{ \App\Models\Accountant::OUTCOME_ID }}"
                                                {{ (old('type_id') ?? $accountantItem->type_id) == \App\Models\Accountant::OUTCOME_ID ? 'selected' : '' }}>
                                                Chi</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-12">
                                    <div class="form-group">
                                        <label for="explain">Note</label>
                                        <textarea class="form-control" id="explain" name="explain"
                                            required>{{ old('explain') ?? $accountantItem->explain }}</textarea>
                                    </div>
                                </div>
                                <div class="col-12 text-center">
                                    <button type="submit" class="btn btn-primary">Submit</button>
                                    <a href="{{ route('accountant.index') }}" type="button"
                                        class="btn btn-warning">Cancel</a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
                <!-- End Filter -->
            </div>
        </div>
    </div>
</section>
@endsection

@section('plugin_scripts')
<!-- Select2 -->
<script src="{{ asset('vendors/admin-lte-3.0.5/plugins/select2/js/select2.full.min.js') }}"></script>

<!-- Summernote -->
<script src="{{ asset('vendors/admin-lte-3.0.5/plugins/summernote/summernote-bs4.min.js') }}"></script>
@endsection

@section('scripts')
<script src="{{ mix('js/accountant.js') }}"></script>
@endsection

resources/views/accountant/index.blade.php
@extends('layouts.master')

@section('title', 'Accountants | English Homestay')

@section('plugin_stylesheets')
<link rel="stylesheet"
    href="{{ asset('vendors/admin-lte-3.0.5/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css') }}">
<link rel="stylesheet"
    href="{{ asset('vendors/admin-lte-3.0.5/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css') }}">
<link rel="stylesheet"
    href="{{ asset('vendors/admin-lte-3.0.5/plugins/datatables-responsive/css/responsive.bootstrap4.min.css') }}">

<!-- SweetAlert2 -->
<link rel="stylesheet"
    href="{{ asset('vendors/admin-lte-3.0.5/plugins/sweetalert2-theme-bootstrap-4/bootstrap-4.min.css') }}">
@endsection

@section('stylesheets')
<style>
    #submit-btn-search {
        margin-bottom: 1rem;
    }

    @media (min-width: 768px) {

        #submit-btn-search,
        #reset-btn-search {
            margin-top: 2rem;
        }

        #submit-btn-search {
            margin-bottom: 0;
        }
    }
</style>
@endsection

@section('content')
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>
                    Accountant <a href="{{ route('accountant.create') }}" class="btn btn-success btn-xs">Add New</a>
                </h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="{{ route('index') }}">Home</a></li>
                    <li class="breadcrumb-item active">Accountant</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <!-- Filter -->
                <div class="card card-primary card-outline">
                    <div class="card-header">
                        <h3 class="card-title">
                            <i class="fas fa-edit"></i>
                            Filter
                        </h3>
                    </div>
                    <div class="card-body">
                        <form role="form" id="accountant-filter">
                            <div class="row">
                                <div class="col-12 col-md-4">
                                    <div class="form-group">
                                        <label for="from-date">From Date</label>
                                        <div class="input-group date" id="from-date" data-target-input="nearest">
                                            <input type="text" class="form-control datetimepicker-input"
                                                data-target="#from-date" value="{{ $fromDate }}" required />
                                            <div class="input-group-append" data-target="#from-date"
                                                data-toggle="datetimepicker">
                                                <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-12 col-md-4">
                                    <div class="form-group">
                                        <label for="to-date">To Date</label>
                                        <div class="input-group date" id="to-date" data-target-input="nearest">
                                            <input type="text" class="form-control datetimepicker-input"
                                                data-target="#to-date" value="{{ $toDate }}" required />
                                            <div class="input-group-append" data-target="#to-date"
                                                data-toggle="datetimepicker">
                                                <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-12 col-md-4">
                                    <div class="row">
                                        <div class="col-12 col-md-6">
                                            <button id="submit-btn-search" type="submit"
                                                class="btn btn-primary btn-block">Submit</button>
                                        </div>
                                        <div class="col-12 col-md-6">
                                            <button id="reset-btn-search" type="button"
                                                class="btn btn-warning btn-block">Reset</button>
                                        </div>
                                    </div>

                                </div>
                            </div>
                        </form>
                    </div>
                </div>
                <!-- End Filter -->
            </div>
        </div>
        <div class="row">
            <div class="col-12 col-md-6">
                <div class="card card-primary">
                    <div class="card-header">
                        <div class="card-title w-100 d-block d-md-flex justify-content-between">
                            <p class="mb-0">Các khoản thu</p>
                            <p class="mb-0" id="sum-income"></p>
                        </div>
                    </div>
                    <div class="card-body">
                        <table id="income-datatable" class="table table-bordered table-striped table-hover">
                            <thead>
                                <tr class="text-center">
                                    <th>Thời gian</th>
                                    <th>Nội dung</th>
                                    <th>Giá trị</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>

                            </tbody>
                            <tfoot>
                                <tr class="text-center">
                                    <th>Thời gian</th>
                                    <th>Nội dung</th>
                                    <th>Giá trị</th>
                                    <th>Action</th>
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>
            </div>
            <div class="col-12 col-md-6">
                <div class="card card-warning">
                    <div class="card-header">
                        <div class="card-title w-100 d-block d-md-flex justify-content-between">
                            <p class="mb-0">Các khoản chi</p>
                            <p id="sum-outcome" class="mb-0"></p>
                        </div>
                    </div>
                    <div class="card-body">
                        <table id="outcome-datatable" class="table table-bordered table-striped table-hover">
                            <thead>
                                <tr class="text-center">
                                    <th>Thời gian</th>
                                    <th>Nội dung</th>
                                    <th>Giá trị</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>

                            </tbody>
                            <tfoot>
                                <tr class="text-center">
                                    <th>Thời gian</th>
                                    <th>Nội dung</th>
                                    <th>Giá trị</th>
                                    <th>Action</th>
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="modal-edit">
        <div class="modal-dialog modal-xl modal-dialog-centered">
            <div class="modal-content">
                <form id="edit-profile-form">
                    <div id="overlay" class="overlay d-none justify-content-center align-items-center">
                        <i class="fas fa-2x fa-sync fa-spin"></i>
                    </div>
                    <div class="modal-header">
                        <h4 class="modal-title">Edit Profile</h4>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">

                    </div>
                    <div class="modal-footer justify-content-between">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Save changes</button>
                    </div>
                </form>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>
</section>
@endsection

@section('plugin_scripts')
<script src="{{ asset('vendors/admin-lte-3.0.5/plugins/moment/moment.min.js') }}"></script>

<!-- DataTables -->
<script src="{{ asset('vendors/admin-lte-3.0.5/plugins/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('vendors/admin-lte-3.0.5/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js') }}"></script>
<script src="{{ asset('vendors/admin-lte-3.0.5/plugins/datatables-responsive/js/dataTables.responsive.min.js') }}">
</script>
<script
    src="{{ asset('vendors/admin-lte-3.0.5/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js') }}">
</script>
<!-- SweetAlert2 -->
<script src="{{ asset('vendors/admin-lte-3.0.5/plugins/sweetalert2/sweetalert2.min.js') }}"></script>
@endsection


@section('scripts')
@if(session('create_accountant'))
<script>
    window.createAccountant = true;
</script>
@endif
@if(session('update_accountant'))
<script>
    window.updateAccountant = true;
</script>
@endif

<script src="{{ mix('js/accountant.js') }}"></script>
@endsection